export const logs = [
    {
      id: 1,
      truckNo: "CG04-AB-1234",
      gatePass: "GP-45678",
      material: "Cement",
      quantity: "20 Tons",
      driver: "Ramesh Kumar",
      vendor: "UltraTech",
      status: "Approved",
    },
    {
      id: 2,
      truckNo: "CG04-CD-5678",
      gatePass: "GP-45679",
      material: "Bricks",
      quantity: "10 Tons",
      driver: "Suresh Yadav",
      vendor: "ACC",
      status: "Completed",
    },
    {
      id: 3,
      truckNo: "CG04-EF-9101",
      gatePass: "GP-45680",
      material: "Steel",
      quantity: "15 Tons",
      driver: "Rajesh Singh",
      vendor: "Tata Steel",
      status: "Draft",
    },
    {
      id: 4,
      truckNo: "CG04-GH-1121",
      gatePass: "GP-45681",
      material: "Sand",
      quantity: "25 Tons",
      driver: "Anil Sharma",
      vendor: "Dalmia Cement",
      status: "Todays out",
    },
  ];